### ISSUE TITLE
TypeScript Compatibility

### ISSUE THREAD

**Issue by pash90** [petegleeson/flushable#1]
I was wondering if there are plans to make the package compatible with TypeScript? If not in the project, then in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)? I created the types in my project and if there's enough requirement, can raise a PR here or on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by petegleeson** [comment]
Personally, I don't have any intention of adding ts support this package. Happy to do so if you want to contribute ts types. I reckon just publish the types from this package. That is the most convenient way to consume them right?

**Comment by pash90** [comment]
Ideally yes. Of you are cool with it, I’ll raise a PR for it

**Comment by pash90** [comment]
@petegleeson I tried adding type definitions in the package itself but it keeps conflicting with flow and I have no experience with it. Therefore, I though it'd be better if I added it instead on DefinitelyTyped. The PR for that is here : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31437. 

Once its approved, I'll raise a PR to update the Readme.
